#!/bin/python3

# Generate full bind9 configuration from a (TopGen) hosts file
# (glsomlo@cert.org, June 2015)
# Updated by Mack :) 2025
#
# We assume a well-behaved hosts file consisting of valid lines
# of the form <ip_addr fqdn> (a file auto-generated by the TopGen
# scraper should work unequivocally; for now, though, we skip any
# additional error checking and validation).
#
# NOTE on DELEGATIONS:
# For each delegated 2nd-level domain (forward) or /24 subnet (reverse),
# we list one or more name server fqdn(s), which will handle lookups
# for that respective domain or subnet.
# We then separately list each name server fqdn with its ip address.
# Each listed delegation name server MUST have a subsequent entry
# containing its IP address, but, for now, we do not enforce that.
# (Failure to provide an IP address for any of the delegation name
# servers results in undefined behavior at this time.
# FIXME: we can either read in the following three hashes from a config
# file programmatically (and add the checks there), or we can add a step
# to check for consistency across the three hashes, if it turns out that
# mistakes are simply TOO easy to make :)


# input hosts file (<ip_addr fqdn> for all virtual Web hosts):
SRC_WHOSTS='/var/lib/topgen/etc/hosts.nginx'
# additional input hosts files (<ip_addr fqdn>):
SRC_XHOSTS=''
# input hosts file (<ip_addr fqdn> for all virtual mail servers):
SRC_MHOSTS='/var/lib/topgen/etc/hosts.vmail'
# input delegations file (hashes to be sourced into our namespace):
SRC_DELEG='/etc/topgen/delegations.dns'
# output hosts file (<ip_addr fqdn> for all virtual DNS servers impersonated):
NAMED_HOSTS='/var/lib/topgen/etc/hosts.named'
# output named.conf
NAMED_CONF='/var/lib/topgen/etc/named.conf'
# output folder for zone files:
NAMED_ZD='/var/lib/topgen/named'
# if "yes", force/overwrite any prior existing configuration
FORCE_GEN='yes'
# if "yes", do not print warnings and a success notification
QUIET_GEN='no'